[package]
name = "ffi-support"
version = "0.1.0"
authors = ["Thom Chiovoloni <tchiovoloni@mozilla.com>"]

[dependencies]
serde_json = "1.0.32"
serde = "1.0.79"
log = "0.4.5"
lazy_static = "1.1.0"
failure = "0.1.3"
failure_derive = "0.1.3"
